### ISSUE TITLE
Tails not working

### ISSUE THREAD

**Issue by FOREVEREALIZE** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#127]
Hello!
Firstly, I would like to say, this is an amazing plugin and makes working with the Avatars sooooo much easier.

However, I couldn't help but notice that Avatars with tails (Gorou, Tighnari, Kirara, Xilonen, Diona and Lynette) don't get their tails rigged and are as such unable to move them. I was wondering whether this is intentional, an inherent technical challenge of the way rigs work, or if it was fixable.

Thanks very much.

**Comment by FOREVEREALIZE** [comment]
Okay, I'm just dumb.

The quick rundown is:
1. Install BoneDynamics and SimpliCage plugins
2. Disable Outlines (it messes with SimpliCage)
3. Import character
4. Once rigged, enable the Physics layer (on the N-Panel)
**Note:** If the N-Panel doesn't seem to show properties when the Armature is selected, go to the scripting tab, select the UI Script, and run it.
5. Select the tail bones (or other bones you want to have physics for)
6. Add Bone Dynamics (on the BoneDynamics N-Panel section)
7. Enable the Cage layer in the N-Panel (w/ Armature selected)
8. Select the Cage bones you want to use for caging (usually legs/thighs and feet).
**Note:** Make sure you select the Cage bones, and not other bones. You can check this by disabling all other layers.
9. Go to SimpliCage in the N-Panel. On there select the Body mesh and set the modes to Chain and Collider
10. Click on Create Cage
11. Customize the BoneDynamics settings in their N-Panel Section.
12. Profit!

I hope you find this useful. If you have any doubts I have found that the people in Festivity's Discord server are super useful.

Happy animating!

**Comment by michael-gh1** [comment]
Hey @FOREVEREALIZE, no worries, you actually did more than most would! Thanks for including steps to get it working in case others run into this issue!

I was going to reply yesterday, but didn't get a chance. I'm glad you were able to get help in Festivity's Discord server! Definitely lots of helpful people in there.

Cheers!

**Comment by FOREVEREALIZE** [comment]
> Hey @FOREVEREALIZE, no worries, you actually did more than most would! Thanks for including steps to get it working in case others run into this issue!
> 
> I was going to reply yesterday, but didn't get a chance. I'm glad you were able to get help in Festivity's Discord server! Definitely lots of helpful people in there.
> 
> Cheers!

Hey, don't worry about it! I understand people have a life (unlike me).
In the end, if I could get it working, I might as well share my wisdom...
