### ISSUE TITLE
Download Nya222's Honkai: Star Rail Shader URL

### ISSUE THREAD

**Issue by YukihimeX** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#53]
Not really an issue but I couldn't download Nya222's HSR Shader using the [link](https://discord.com/channels/894925535870865498/1127604826885328926/1143189750665195520) @michael-gh1 provided cuz the channel grayed out for me. 

But I was able to download it from the [Amatsuri ](https://discord.com/channels/894925535870865498/895312563817021500) server, in case anyone else had a hard time like me.

**Nya222's Honkai Star Rail Shader**
[**DOWNLOAD**](https://discord.com/channels/894925535870865498/895312563817021500/1146773668299538432) https://discord.com/channels/894925535870865498/895312563817021500/1146773668299538432

**Comment by Zerytas** [comment]
Hi I don't know what went wrong but I couldn't download shaders on both link (including Amatsuri's) .

Would you mind sharing it with me? Both look just like this. 


![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/145338299/31375d3b-b8a3-4fbb-8c5a-c7eb875a11b7)

![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/145338299/ad3c3415-fcbc-440f-9453-32549cc298eb)

**Comment by michael-gh1** [comment]
@Zerytas You should be able to access it once you join Festivity's server, `Omatsuri` (which happens to be one letter different from `Amatsuri`).

You can find the server invite in Festivity's repo: https://github.com/festivities/Blender-miHoYo-Shaders
Just do a quick search on the page and you should be able to find it.

It's in the #sharing forum on the server in case the link continues to not work.

**Comment by Zerytas** [comment]
Found it. Thanks a bunch!

One small step~

![thanks](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/145338299/2d3bb908-a96f-4330-8e2a-de9564cb8937)
