### ISSUE TITLE
Lighting does not change when I try moving the main light source

### ISSUE THREAD

**Issue by Nedarb183** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#79]
When I move the main lighting object the character lighting does not change, in both material and render view.

**Comment by michael-gh1** [comment]
Hi @Nedarb183, are you moving the light or rotating it?

There should be an Empty called `Light Direction` if you're using the latest shader (V3 for Genshin Impact/Punishing Gray Raven).
If you're using V1/V2 shader the Empty is called `Main Light Direction`.

Other information that would be helpful is what character/game you're working with.

**Comment by Nedarb183** [comment]
Hi @michael-gh1, thank you very much for the reply
I am using v3 of the shader and have tried rotating the light direction empty, but it does not change the lighting. I am using the genshin impact .fbx models from this asset download.
https://github.com/zeroruka/GI-Assets
From there I followed the steps outlined in this video: https://www.youtube.com/watch?v=vWfd3NIezpQ
I seem to be having this problem with all of the models. I did not create outlines but I would doubt that this would be causing the problem.
Thanks again for the help.

**Comment by michael-gh1** [comment]
I think you might be missing the Light Vectors geometry node which typically gets run when setting up outlines. See my screenshot below.

If your body part meshes are not joined, you may need to add this to each body part (screenshot below has my meshes joined to one mesh named `Body`).

![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/8632035/05908817-3ef2-449f-acab-29ce49be9ac4)

Lighting/shading is handled using Geometry Nodes in the V3 shader, which helped improve performance drastically compared to the previous version of the shader.

Considering this, I may need to separate the Light Vector setup and Outlines setup operations as currently they are under the same `Set Up Geometry Nodes` operation.

**Comment by Nedarb183** [comment]
You were absolutely right. Not setting up the outline was causing the problem. It seems to be working perfectly fine now.
Thank you so much for the help!

**Comment by michael-gh1** [comment]
Awesome! Glad I could help out!
