### ISSUE TITLE
Failed to add shader to a second character

### ISSUE THREAD

**Issue by shieldkeke** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#91]
![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/89073784/7c0889e0-f717-4b9e-ae04-7cf9db559b71)
![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/89073784/6e30d78b-5d3e-4350-a352-9a03600fb132)
![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/89073784/4437a715-faba-42ac-a633-f86ea26f2dcc)

**Comment by michael-gh1** [comment]
Heya, setting up multiple characters in the same file isn't supported.

Set the characters up in separate files and then append/link them both into a new file.

**Comment by michael-gh1** [comment]
Closing the issue, but please don't hesitate to reach out if you have any further questions.
